---
- name: Verify if SDKMAN Is Installed
  stat:
    path: "~/.sdkman/"
  register: "sdkman_installed"

- name: Install SDKMAN
  shell: 'curl -s http://get.sdkman.io | bash'
  args:
    executable: /bin/bash
    warn: no
  when: not sdkman_installed.stat.exists

- name: Add SDKMAN in .zshrc
  lineinfile:
    dest: ~/.zshrc
    regexp: 'sdkman-init.sh'
    line: 'source $HOME/.sdkman/bin/sdkman-init.sh'
    state: present