- name: Updating Homebrew
  homebrew:
    update_homebrew: true

- name: Installing Homebrew Packages
  homebrew:
    name: "{{ item.name|default(item) }}"
    state: present
  loop: "{{ homebrew }}"

- name: Refreshing sudo Cache
  command: "echo none"
  become: yes

- name: Installing Homebrew Cask Packages
  homebrew_cask:
    name: "{{ item.name|default(item) }}"
    state: present
    options: "{{ item.install_options | default(omit) }}"
    accept_external_apps: yes
  ignore_errors: true
  loop: "{{ homebrew_cask }}"
  notify:
    - brew cask doctor
