---
- name: Pull dotfiles Periodically
  cron:
    name: 'pull dotfiles'
    minute: '0'
    job: 'cd ~/dotfiles && git reset --hard origin/master && git clean -fxd && git pull -q > ~/dotfiles-sync-log'