---
- name: Updating Homebrew
  homebrew:
    update_homebrew: true

- name: Installing JDK
  homebrew_cask:
    name: adoptopenjdk
    state: present
    accept_external_apps: yes
  ignore_errors: true

- name: Installing Homebrew Packages
  homebrew:
    name: "{{ item.name|default(item) }}"
    state: present
  loop: "{{ homebrew }}"
  ignore_errors: true


- name: Refreshing sudo Cache
  command: "echo none"
  changed_when: false
  become: yes

- name: Installing Homebrew Cask Packages
  homebrew_cask:
    name: "{{ item.name|default(item) }}"
    state: present
    options: "{{ item.install_options | default(omit) }}"
    accept_external_apps: yes
  ignore_errors: true
  loop: "{{ homebrew_cask }}"
  notify:
    - brew cask doctor

- name: Setup Docker Cleanup
  import_tasks: docker-cleanup.yml
