---
- name: Dock Configuration
  include: dock-config.yml

- name: Finder Configuration
  include: finder-config.yml

- name: Safari Configuration
  include: safari-config.yml

- name: Set Terminal Settings
  osx_defaults: domain=com.apple.Terminal key={{ item.key }} type={{ item.type }} value={{ item.value }}
  with_items:
    - { key: "SecureKeyboardEntry", type: "bool", value: "true" }

- name: Set Global Settings
  osx_defaults: domain=NSGlobalDomain key={{ item.key }} type={{ item.type }} value={{ item.value }}
  with_items:
    - { key: "NSTableViewDefaultSizeMode", type: "int", value: "1" }
    - { key: "NSNavPanelExpandedStateForSaveMode", type: "bool", value: "true" }
    - { key: "NSNavPanelExpandedStateForSaveMode2", type: "bool", value: "true" }
    - { key: "PMPrintingExpandedStateForPrint", type: "bool", value: "true" }
    - { key: "PMPrintingExpandedStateForPrint2", type: "bool", value: "false" }
    - { key: "NSDocumentSaveNewDocumentsToCloud", type: "bool", value: "false" }
    - { key: "NSTextShowsControlCharacters", type: "bool", value: "true" }
    - { key: "ApplePressAndHoldEnabled", type: "bool", value: "false" }
    - { key: "AppleFontSmoothing", type: "int", value: "2" }
    - { key: "AppleShowAllExtensions", type: "bool", value: "true" }
    - { key: "NSAutomaticSpellingCorrectionEnabled", type: "bool", value: "false" }
    - { key: "com.apple.springing.delay", type: "float", value: "1.0" }

- name: Create ~/Screenshots Directory
  file:
    state: directory
    path: "{{ ansible_env.HOME }}/Desktop/Screenshots"

- name: Set Remaining Settings
  osx_defaults: domain={{ item.domain }} key={{ item.key }} type={{ item.type }} value={{ item.value }}
  with_items:
    - { domain: "com.apple.DiskUtility", key: "DUDebugMenuEnabled", type: "bool", value: "true" }
    - { domain: "com.apple.DiskUtility", key: "image", type: "bool", value: "true" }
    - { domain: "com.apple.print.PrintingPrefs", key: "Quit When Finished", type: "bool", value: "true" }
    - { domain: "com.apple.mail", key: "AddressesIncludeNameOnPasteboard", type: "bool", value: "false" }
    - { domain: "com.apple.frameworks.diskimages", key: "auto-open-ro-root", type: "bool", value: "true" }
    - { domain: "com.apple.frameworks.diskimages", key: "auto-open-rw-root", type: "bool", value: "true" }
    - { domain: "com.apple.desktopservices", key: "DSDontWriteNetworkStores", type: "bool", value: "true" }
    - { domain: "com.apple.desktopservices", key: "DSDontWriteUSBStores", type: "bool", value: "true" }
    - { domain: "com.apple.screencapture", key: "location", type: "string", value: "{{ ansible_env.HOME }}/Desktop/Screenshots" }
    - { domain: "com.apple.screencapture", key: "type", type: "string", value: "png" }
    - { domain: "com.apple.screencapture", key: "disable-shadow", type: "bool", value: "true" }
    - { domain: "com.apple.BluetoothAudioAgent", key: "Apple Bitpool Min (editable)", type: "int", value: "40" }
    - { domain: "com.apple.driver.AppleBluetoothMultitouch.trackpad", key: "Clicking", type: "int", value: "1" }
    - { domain: "com.apple.SoftwareUpdate", key: "ScheduleFrequency", type: "int", value: "1" }
    - { domain: "com.apple.SoftwareUpdate", key: "AutomaticCheckEnabled", type: "bool", value: "true" }
    - { domain: "com.apple.SoftwareUpdate", key: "AutomaticDownload", type: "int", value: "1" }
    - { domain: "com.apple.SoftwareUpdate", key: "CriticalUpdateInstall", type: "int", value: "1" }
    - { domain: "com.apple.commerce", key: "AutoUpdate", type: "bool", value: "true" }
    - { domain: "com.apple.helpviewer", key: "DevMode", type: "bool", value: "true" }
    - { domain: "com.apple.ImageCapture", key: "disableHotPlug", type: "bool", value: "true" }
  notify:
    - Kill SystemUIServer

- name: Use Plaintext Mode for new TextEdit Documents
  osx_defaults: domain=com.apple.TextEdit key=RichText type=int value=0

- name: Open and Save Files as UTF-8 in TextEdit
  osx_defaults: domain=com.apple.TextEdit key={{ item }} type=int value=4
  with_items:
    - PlainTextEncoding
    - PlainTextEncodingForWrite

- name: Enable debug menu in Disk Utility
  osx_defaults: domain=com.apple.DiskUtility key={{ item }} type=bool value=true
  with_items:
    - DUDebugMenuEnabled
    - advanced-image-options

- name: Show the ~/Library folder
  shell: chflags nohidden ~/Library

- name: Prevent Time Machine from prompting to use new hard drives as backup volume
  osx_defaults: domain=com.apple.TimeMachine key=DoNotOfferNewDisksForBackup type=bool value=true

- name: Show the main window when launching the Activity Monitor
  osx_defaults: domain=com.apple.ActivityMonitor key=OpenMainWindow type=bool value=true

- name: Visualize CPU usage in the Activity Monitor Dock icon
  osx_defaults: domain=com.apple.ActivityMonitor key=IconType type=int value=5

- name: Show all processes in Activity Monitor
  osx_defaults: domain=com.apple.ActivityMonitor key=ShowCategory type=int value=0

- name: Sort Activity Monitor results by CPU usage
  osx_defaults: domain=com.apple.ActivityMonitor key=SortColumn value="CPUUsage"

- name: Sort activity monitor direction
  osx_defaults: domain=com.apple.ActivityMonitor key=SortDirection type=int value=0

- name: Make Safari's search banners default to Contains instead of Starts With
  osx_defaults: domain=com.apple.Safari key=FindOnPageMatchesWordStartsOnly type=bool value=false

- name: Remove useless icons from Safari's bookmarks bar
  osx_defaults: domain=com.apple.Safari key=ProxiesInBookmarksBar state=absent

- name: Disable Safari's thumbnail cache
  osx_defaults: domain=com.apple.Safari key=DebugSnapshotsUpdatePolicy type=int value=2

- name: Show Battery Percent
  osx_defaults: domain=com.apple.menuextra.battery key=ShowPercent type=string value="YES"

- name: Enable Tap to Click
  osx_defaults: domain=com.apple.AppleMultitouchTrackpad key=Clicking type=int value=1

- name: Disable CrashReporter
  command: defaults write com.apple.CrashReporter DialogType -string "none"

- name: Enable HostInfo
  command: defaults write /Library/Preferences/com.apple.loginwindow AdminHostInfo HostName
  become: true

- name: Add LoginWindowText
  command: "defaults write /Library/Preferences/com.apple.loginwindow LoginwindowText -string '{{ login_window_text }}'"
  become: true

- name: Unhide Directories
  become: true
  command: "chflags nohidden /{{ item }}"
  with_items:
    - tmp
    - opt
    - etc
    - var

- name: Run iTerm At Login
  command: osascript -e 'tell application "System Events" to make login item at end with properties {path:"/Applications/iTerm.app", hidden:true}'
  ignore_errors: true
  become: true
